### ISSUE TITLE
About instructions for the codes

### ISSUE THREAD

**Issue by YuJungHeo** [Sid2697/EgoProceL-egocentric-procedure-learning#1]
Hello @Sid2697,

I am very interested in procedure learning on egocentric videos.
I have tried to run the released codes, but it failed due to a lack of instructions.

When will you upload the instruction for the codes?

Regards,
Yu-Jung

**Comment by Sid2697** [comment]
Hello @YuJungHeo, thank you for your interest in our work! I will update the instructions for the code by this weekend. Appreciate the patience!

Regards,
Siddhant Bansal

**Comment by YuJungHeo** [comment]
@Sid2697, Thank you for your prompt response! We are looking forward to the codes :)

Regards,
Yu-Jung

**Comment by Sid2697** [comment]
@YuJungHeo I have updated the instructions. Have fun learning procedures :)
