### ISSUE TITLE
Memory & Time Cost for the experiments.

### ISSUE THREAD

**Issue by wjun0830** [Sid2697/EgoProceL-egocentric-procedure-learning#2]
Hello.
First of all, thank you for your interesting work.

Can you provide the training hours to run the experiment? (With the details of GPU)

Thank you.
Regards.

**Comment by Sid2697** [comment]
Hello @wjun0830,

Thank you for your interest in our work!

At the time of training we use two NVIDIA GeForce RTX 2080 Ti. Regarding time, if we train EmbedNet for 10000 epochs, on a task consisting of approximately 30 videos, it takes on average 3 hours. Regarding memory, if the length of videos is reasonable (10-15 minutes) 64GB RAM suffices. However, if the length of videos is higher, one has to increase the RAM. We have used at max 90GB RAM for experiments.

I hope this information clears your doubts. All the best!

Regards,
Siddhant Bansal

**Comment by Sid2697** [comment]
Closing the issue assuming the question was answered. Please feel free to reopen the issue for further clarification!
