### ISSUE TITLE
Confusion about data paths

### ISSUE THREAD

**Issue by kaanaykutkabakci** [Sid2697/EgoProceL-egocentric-procedure-learning#3]
Hello, i am trying to train only Sandwich videos on my pc. But it seems i am doing some wrong things. For example in demo_config.yaml what is the difference between CMU_KITCHEN: VIDEOS_PATH and TCC: DATA_PATH? 

In addition, what should be the folder structure for videos? as is annotations folder structure or different? 

Could you please share a detailed data folder structure explanation and example config file for Sandwich videos?

**Comment by SayeedChowdhury** [comment]
Hi @kaanaykutkabakci , I am having similar confusion, could you please reply how you solved it?
Also, @Sid2697, can you please explain these questions? would really help me, thanks

**Comment by Sid2697** [comment]
Answered here: #7
