### ISSUE TITLE
Download links not working

### ISSUE THREAD

**Issue by vknoben** [Sid2697/EgoProceL-egocentric-procedure-learning#6]
Hi, thank you for sharing your work! Sounds very interersting!
I can't access the OneDrive download links. It just say 404 page not found. 
Would love to take a closer look at the dataset and its annotations:)

**Comment by Sid2697** [comment]
Hello, thanks for bringing this up. Looks like I no longer have access to that OneDrive account. I have uploaded the annotations here: https://drive.google.com/drive/folders/17u7ReqPOJ29lbVZT8PDEd5dN17VBqS5Q?usp=share_link

I will need more time to upload the videos for assembling and disassembling PC. I'll reply here once that is done. Meanwhile, you can explore the annotations and videos for other datasets within EgoProceL.

Good luck!

**Comment by vknoben** [comment]
Wow, thanks a lot for such a quick response! Looking forward to the pc assembly videos. Thanks a lot!

**Comment by Sid2697** [comment]
Hello @anjelomerte, here is the link to the videos: https://drive.google.com/drive/folders/19QofEX1tcfmU3fO2DAwGV8iiBZPAiRuI?usp=share_link

This is a temporary link. We are working on uploading the videos to a more stable place. This might take a couple of weeks. Meanwhile, please use this link.
